# Generated by Django 4.2.1 on 2023-05-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(max_length=20)),
                ('type', models.TextField(max_length=10)),
                ('model', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
